feat[SBD-529] : Se agrega caso de uso generar reporte de estadisticas de customer
3pilab/stan-facom pull request #237
Opened 2022-02-09 23:37 UTC by Alejandro2134

## PR Type
¿Qué tipo de cambio introduce este PR? 

- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (Sin cambios en funcionalidades, Sin cambios al API)
- [ ] Cambios en la documentacion

## Que es lo que modifica?

Se agrega caso de uso generar reporte de estadisticas de customer

-se agrega definicion del api para  ruta generate-stats-report  en oas
-se agrega la ruta para generar reporte de estadisticas de customer
-se crea funcion para ejecutar el caso de uso desde el controlador
-se agrega la logica necesaria para generar reporte de estadisticas de customer

Issue Number: SBD-529

## Introduce un cambio que rompa alguna funcionalidad existente?

- [ ] Si
- [x] No

## Otras observaciones
N/A

2022-02-11 16:34 UTC, paintoxic requested changes

2022-02-11 16:34 UTC, paintoxic commented on src/domain/modules/customers/app_business_rules/customer/use_cases/get_report_stats.ts
> +        for await (const artisan of stats.artisan) {
por que esto tiene un await si el metodo que llama no es asyncrono ??

2022-02-11 16:34 UTC, paintoxic commented on src/domain/modules/customers/app_business_rules/customer/use_cases/get_report_stats.ts
> +        data.forEach((items) => {
No es claro por que las dos iteraciones, seguro que usar un foreach es la mejor solucion ??

2022-02-11 16:34 UTC, paintoxic commented on src/domain/modules/customers/app_business_rules/customer/use_cases/get_report_stats.ts
> +                if (item != 'Customer Type' && item != 'Customer Business') {
Si van a haber comparaciones con cosas estaticas lo mejor es dejarlas declaradas como constantes del scope

2022-02-11 19:52 UTC, Alejandro2134 commented on src/domain/modules/customers/app_business_rules/customer/use_cases/get_report_stats.ts
> +        for await (const artisan of stats.artisan) {
fixed

2022-02-11 19:52 UTC, Alejandro2134 commented on src/domain/modules/customers/app_business_rules/customer/use_cases/get_report_stats.ts
> +                if (item != 'Customer Type' && item != 'Customer Business') {
fixed

2022-02-11 19:57 UTC, Alejandro2134 commented on src/domain/modules/customers/app_business_rules/customer/use_cases/get_report_stats.ts
> +        data.forEach((items) => {
La primera es para recorrer un arreglo de objetos y la segunda para recorrer cada objeto dentro del arreglo

2022-02-21 14:16 UTC, paintoxic approved these changes

2022-02-21 14:49 UTC, merged